### ISSUE TITLE
Cuadro comparativo

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Ariadnamonserrat10#1]
[
[Cuadro comparativo.docx](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Ariadnamonserrat10/files/9474503/Cuadro.comparativo.docx)
](url)
Alumna: Ariadna Monserrat López Aparicio
1BS

**Comment by AmeliReyesHernandez** [comment]
18.8 de 20

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
